name: Smart CI Pipeline

on:
  repository_dispatch:
    types: [trigger-ci]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Show Task Info
        run: |
          echo "Task: ${{ github.event.client_payload.task }}"
          echo "Priority: ${{ github.event.client_payload.priority }}"