name: Smart CI Pipeline

on:
  repository_dispatch:
    types: [trigger-ci]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run Smart CI/CD
        run: echo "🚀 Triggered from Flask App!"